#- hosts: minions
#  remote_user: root
#  tasks:
     - name: join node to master
       command: kubeadm join --token {{lookup('file','roles/master/files/mastersrv')}} 
       args:
         creates: /etc/kubernetes/kubelet.conf
